### ISSUE TITLE
Lerna package release version does not render correctly in GitHub commit message

### ISSUE THREAD

**Issue by KasperZutterman** [TREEcg/bucketizers#7]
![image](https://user-images.githubusercontent.com/21260838/140488411-94eec45f-380b-42dc-8fa9-1998637de3ea.png)

**Comment by KasperZutterman** [comment]
Maybe there should be the field version like here inside lerna.json:
https://github.com/rubensworks/jbr.js/blob/5fff4956b2752f523a21378485ddceb1cd3e69df/lerna.json#L17

**Comment by ddvlanck** [comment]
This could be caused because the `version` field is set to `independent`. I changed this to a more general message: `Bump to new release version` in [this](https://github.com/TREEcg/bucketizers/commit/19eec4e31cae7885c82b36374b83d20641738250) commit
